/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/event`; params?: Router.UnknownInputParams; } | { pathname: `/forgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/homePage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/pressables`; params?: Router.UnknownInputParams; } | { pathname: `/welcome2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/general`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/mentor`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/sponser`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/event`; params?: Router.UnknownOutputParams; } | { pathname: `/forgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/homePage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/pressables`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome2`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/signUp/general`; params?: Router.UnknownOutputParams; } | { pathname: `/signUp/mentor`; params?: Router.UnknownOutputParams; } | { pathname: `/signUp/sponser`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/event${`?${string}` | `#${string}` | ''}` | `/forgotPassword${`?${string}` | `#${string}` | ''}` | `/homePage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/payment${`?${string}` | `#${string}` | ''}` | `/pressables${`?${string}` | `#${string}` | ''}` | `/welcome2${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/profile/edit-profile${`?${string}` | `#${string}` | ''}` | `/profile/profile${`?${string}` | `#${string}` | ''}` | `/signUp/general${`?${string}` | `#${string}` | ''}` | `/signUp/mentor${`?${string}` | `#${string}` | ''}` | `/signUp/sponser${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/event`; params?: Router.UnknownInputParams; } | { pathname: `/forgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/homePage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/pressables`; params?: Router.UnknownInputParams; } | { pathname: `/welcome2`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/general`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/mentor`; params?: Router.UnknownInputParams; } | { pathname: `/signUp/sponser`; params?: Router.UnknownInputParams; };
    }
  }
}
